pub(super) const SCHEMA: &str = r#"
BEGIN;
CREATE TABLE users(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE passkeys(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,credential_json TEXT NOT NULL,created_at INTEGER NOT NULL,last_used INTEGER);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('browser')),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE ceremonies(id TEXT PRIMARY KEY,kind TEXT NOT NULL,user_id TEXT,meta_json TEXT NOT NULL DEFAULT '{}',state_json TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL);
CREATE TABLE workspace_members(workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL CHECK(role IN ('owner','operator','viewer')),joined_at INTEGER NOT NULL,PRIMARY KEY(workspace_id,user_id));
CREATE TABLE workspace_invites(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,role TEXT NOT NULL CHECK(role IN ('operator','viewer')),created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,used_at INTEGER);
CREATE TABLE enrollment_tokens(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,used_at INTEGER);
CREATE TABLE devices(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,hostname TEXT NOT NULL,platform TEXT NOT NULL,arch TEXT NOT NULL,identity_public_key TEXT NOT NULL UNIQUE,transport_public_key TEXT NOT NULL,lock_hash TEXT NOT NULL DEFAULT '',lock_generation INTEGER NOT NULL DEFAULT 0,version TEXT NOT NULL,capabilities TEXT NOT NULL DEFAULT '[]',last_seen INTEGER,created_at INTEGER NOT NULL);
CREATE TABLE revoked_devices(id TEXT PRIMARY KEY,identity_public_key TEXT NOT NULL,revoked_at INTEGER NOT NULL);
CREATE TABLE processes(id TEXT PRIMARY KEY,device_id TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,origin TEXT NOT NULL CHECK(origin IN ('browser','cli','api','mcp','ssh')),status TEXT NOT NULL CHECK(status IN ('starting','running','exited','lost')),terminal INTEGER NOT NULL,exit_code INTEGER,signal TEXT,error TEXT,created_by TEXT NOT NULL REFERENCES users(id),created_at INTEGER NOT NULL,started_at INTEGER,completed_at INTEGER);
CREATE TABLE clients(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('browser','cli','api')),name TEXT NOT NULL,public_key TEXT NOT NULL,scopes TEXT NOT NULL DEFAULT '[]',credential_id TEXT,grant TEXT,assertion TEXT,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL DEFAULT 0,last_used INTEGER);
CREATE TABLE cli_authorizations(id TEXT PRIMARY KEY,device_code_hash TEXT NOT NULL UNIQUE,user_code_hash TEXT NOT NULL UNIQUE,client_id TEXT NOT NULL,public_key TEXT NOT NULL,lifetime TEXT NOT NULL,user_id TEXT REFERENCES users(id) ON DELETE CASCADE,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,approved_at INTEGER,exchanged_at INTEGER);
CREATE TABLE ssh_keys(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,algorithm TEXT NOT NULL,key_data TEXT NOT NULL UNIQUE,public_key TEXT NOT NULL,client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,created_at INTEGER NOT NULL,last_used INTEGER);
CREATE TABLE mcp_clients(id TEXT PRIMARY KEY,name TEXT NOT NULL,redirect_uris TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE mcp_requests(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,client_id TEXT NOT NULL REFERENCES mcp_clients(id) ON DELETE CASCADE,redirect_uri TEXT NOT NULL,state TEXT NOT NULL,scope TEXT NOT NULL,code_challenge TEXT NOT NULL,resource TEXT NOT NULL,prepared_grant TEXT,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE mcp_grants(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,client_id TEXT NOT NULL REFERENCES mcp_clients(id) ON DELETE CASCADE,name TEXT NOT NULL,grant TEXT NOT NULL,grant_signature TEXT NOT NULL,client_control_id TEXT NOT NULL,credential_id TEXT NOT NULL,control_grant TEXT NOT NULL,control_assertion TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,last_used INTEGER,revoked_at INTEGER);
CREATE TABLE oauth_codes(code_hash TEXT PRIMARY KEY,grant_id TEXT NOT NULL REFERENCES mcp_grants(id) ON DELETE CASCADE,redirect_uri TEXT NOT NULL,code_challenge TEXT NOT NULL,resource TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE oauth_tokens(token_hash TEXT PRIMARY KEY,grant_id TEXT NOT NULL REFERENCES mcp_grants(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('access','refresh')),expires_at INTEGER NOT NULL);
CREATE TABLE request_nonces(principal TEXT NOT NULL,nonce_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(principal,nonce_hash));
CREATE TABLE events(id INTEGER PRIMARY KEY AUTOINCREMENT,workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE,user_id TEXT REFERENCES users(id) ON DELETE SET NULL,device_id TEXT REFERENCES devices(id) ON DELETE SET NULL,kind TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);
CREATE INDEX idx_members_user ON workspace_members(user_id);
CREATE INDEX idx_devices_workspace ON devices(workspace_id);
CREATE INDEX idx_processes_device ON processes(device_id,created_at DESC);
CREATE INDEX idx_events_workspace ON events(workspace_id,created_at DESC);
CREATE INDEX idx_nonces_expiry ON request_nonces(expires_at);
PRAGMA user_version=1;
COMMIT;
"#;
