[package]
name = "rc-api-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek = { workspace = true, features = ["pkcs8"] }
rand.workspace = true
rc-crypto = { path = "../rc-crypto" }
rc-protocol = { path = "../rc-protocol" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
