mod account;
mod commands;
mod component_cli;
mod control_client;
mod help;
mod service;

use clap::{CommandFactory, Parser, Subcommand};

#[derive(Parser)]
#[command(
    name = "rc",
    version = rc_cli::VERSION,
    about = "Remote control and device node",
    long_about = "Control enrolled machines, manage the local RC Node, and configure SSH compatibility.",
    after_help = "Installed WebAssembly components may add commands dynamically. Run `rc commands` to inspect them."
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Print the installed RC version.
    Version,
    /// Authorize this CLI through a passkey-backed browser session.
    Login {
        /// RC server URL. Defaults to RC_URL, saved configuration, or the hosted service.
        #[arg(long)]
        url: Option<String>,
        /// Authorization lifetime: 30d, 7d, 1d, or never.
        #[arg(long, default_value = "never")]
        expires: String,
    },
    /// Revoke and remove this CLI's saved account authorization.
    Logout,
    /// Enroll this machine as an RC Node.
    Enroll {
        /// One-time enrollment token generated by an RC workspace owner.
        token: String,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Device display name. Defaults to the configured name or hostname.
        #[arg(long)]
        name: Option<String>,
        /// Override the local RC state directory.
        #[arg(long = "state-dir")]
        state_dir: Option<String>,
    },
    /// Show local enrollment and remote Node status.
    Status {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Override the local RC state directory.
        #[arg(long = "state-dir")]
        state_dir: Option<String>,
    },
    /// List devices available to the signed-in account or API key.
    Devices {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Explicit proof-of-possession API credential.
        #[arg(long)]
        token: Option<String>,
    },
    /// Manage an enrolled device.
    Device {
        #[command(subcommand)]
        command: DeviceCommand,
    },
    /// Read or change local Node configuration.
    Config {
        #[command(subcommand)]
        command: Option<ConfigCommand>,
    },
    /// Run the local Node, or execute a command on a remote device.
    ///
    /// With no DEVICE, starts the local Node in the foreground. With DEVICE,
    /// everything after `--` is executed remotely without losing argument boundaries.
    Run {
        /// Device ID, unique ID prefix, or unique case-insensitive name.
        device: Option<String>,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Explicit proof-of-possession API credential.
        #[arg(long)]
        token: Option<String>,
        /// Override the local RC state directory when running the local Node.
        #[arg(long = "state-dir")]
        state_dir: Option<String>,
        /// Command and arguments to execute remotely.
        #[arg(last = true)]
        command: Vec<String>,
    },
    /// Open an interactive terminal on a remote device.
    Shell {
        /// Device ID, unique ID prefix, or unique case-insensitive name.
        device: String,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Explicit proof-of-possession API credential.
        #[arg(long)]
        token: Option<String>,
    },
    /// Register and manage OpenSSH public keys for RC SSH compatibility.
    #[command(name = "ssh-key")]
    SshKey {
        #[command(subcommand)]
        command: SshKeyCommand,
    },
    /// Print OpenSSH host entries for available RC devices.
    #[command(name = "ssh-config")]
    SshConfig {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Explicit proof-of-possession API credential.
        #[arg(long)]
        token: Option<String>,
    },
    /// Bridge OpenSSH standard I/O to the RC SSH gateway.
    #[command(name = "ssh-proxy")]
    SshProxy {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
    },
    /// Manage the per-user RC Node background service.
    Service {
        #[command(subcommand)]
        command: ServiceCommand,
    },
    /// Upgrade the native RC platform while keeping installed components.
    Upgrade,
    /// Unregister this Node and remove its local service, state, and binary.
    Uninstall {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Override the local RC state directory.
        #[arg(long = "state-dir")]
        state_dir: Option<String>,
    },
}

#[derive(Subcommand)]
enum SshKeyCommand {
    /// Register an OpenSSH public key.
    Add {
        /// Friendly key name.
        #[arg(long)]
        name: Option<String>,
        /// Public key file. Defaults to ~/.ssh/id_ed25519.pub.
        file: Option<String>,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
    },
    /// List registered OpenSSH public keys.
    List {
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
    },
    /// Revoke a registered OpenSSH public key.
    Remove {
        /// RC SSH key ID.
        id: String,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
    },
}

#[derive(Subcommand)]
enum DeviceCommand {
    /// Remove a device immediately and leave a revocation tombstone.
    Delete {
        /// Device ID, unique ID prefix, or unique case-insensitive name.
        id: String,
        /// RC server URL.
        #[arg(long)]
        url: Option<String>,
        /// Explicit proof-of-possession API credential.
        #[arg(long)]
        token: Option<String>,
    },
}

#[derive(Subcommand)]
enum ConfigCommand {
    /// Show the effective local Node configuration.
    Show,
    /// Print the local Node configuration file path.
    Path,
    /// Set `server` or `name` in the local Node configuration.
    Set {
        /// Configuration key: server or name.
        key: String,
        /// Configuration value.
        value: Vec<String>,
    },
    /// Remove `server` or `name` from the local Node configuration.
    Unset {
        /// Configuration key: server or name.
        key: String,
    },
}

#[derive(Subcommand)]
enum ServiceCommand {
    /// Install and start the per-user RC Node service.
    Install,
    /// Start the installed per-user RC Node service.
    Start,
    /// Stop the per-user RC Node service.
    Stop,
    /// Print service-manager status.
    Status,
    /// Stop and remove the per-user RC Node service definition.
    Uninstall,
}

#[tokio::main]
async fn main() {
    if std::env::args().nth(1).as_deref() == Some("__process-runner") {
        std::process::exit(rc_node::run_process_runner());
    }
    let args = std::env::args_os().collect::<Vec<_>>();
    if help::top_level_requested(&args) {
        help::print(&Cli::command());
        return;
    }
    match component_cli::dispatch_if_component_command() {
        Ok(Some(code)) => std::process::exit(code),
        Ok(None) => {}
        Err(error) => {
            eprintln!("error: {error}");
            std::process::exit(1);
        }
    }
    let cli = Cli::parse();
    if let Err(error) = commands::run(cli.command).await {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}
