import { CopyField, DocTable } from "./components";
import type { DocArticle } from "./types";
import { PUBLIC_URL } from "../../../src/config";

export function cliArticle(): DocArticle {
  return {
    slug: "cli",
    title: "CLI",
    intro: "Install, authenticate, enroll devices, and control machines with rc.",
    copy: true,
    sections: [
      {
        id: "install",
        title: "Install",
        body: <>
          <CopyField value={`curl -fsSL ${PUBLIC_URL}/install.sh | sh`}/>
          <p>The installer downloads the signed binary for the current operating system and architecture to <code>~/.local/bin/rc</code>. macOS and Linux are supported.</p>
          <p>For a machine that will run the RC Node, prefer the enrollment command generated by the Devices page. It installs the binary, consumes the one-time enrollment token, and installs the background service.</p>
        </>,
      },
      {
        id: "login",
        title: "Sign in",
        body: <>
          <CopyField value="rc login"/>
          <CopyField value="rc login --expires 7d"/>
          <p><code>login</code> generates a local Ed25519 control key and opens RC for passkey approval. The default lifetime is until revoked.</p>
          <p>Finite values are <code>1h</code>, <code>1d</code>, <code>7d</code>, <code>30d</code>, <code>90d</code>, <code>180d</code>, and <code>1y</code>.</p>
          <p><code>rc logout</code> revokes the hosted CLI session and removes the local account session.</p>
        </>,
      },
      {
        id: "commands",
        title: "Commands",
        body: <DocTable><thead><tr><th>Command</th><th>Description</th></tr></thead><tbody>
          <tr><td><code>rc devices</code></td><td>List devices, workspaces, online state, and Node version.</td></tr>
          <tr><td><code>rc shell DEVICE</code></td><td>Open the machine's login shell in the current terminal.</td></tr>
          <tr><td><code>rc run DEVICE -- CMD...</code></td><td>Run one command remotely and stream its output.</td></tr>
          <tr><td><code>rc actions</code></td><td>List saved Actions.</td></tr>
          <tr><td><code>rc action run ACTION --device DEVICE</code></td><td>Run a saved Action. Add <code>--confirm</code> when the Action requires confirmation.</td></tr>
          <tr><td><code>rc status</code></td><td>Show local enrollment and hosted device status.</td></tr>
          <tr><td><code>rc enroll TOKEN</code></td><td>Enroll this machine. Optional flags: <code>--name</code>, <code>--url</code>, <code>--state-dir</code>.</td></tr>
          <tr><td><code>rc service install|start|stop|status|uninstall</code></td><td>Manage the per-user background Node service.</td></tr>
          <tr><td><code>rc update</code></td><td>Verify and install a signed newer Node release, then restart the service if installed.</td></tr>
          <tr><td><code>rc device delete ID</code></td><td>Owner-authorized remote removal followed by hosted device deletion.</td></tr>
          <tr><td><code>rc config show|path|set|unset</code></td><td>Read or modify the default RC server and enrollment name.</td></tr>
          <tr><td><code>rc uninstall</code></td><td>Remove the service, unregister the device when possible, delete local RC state, and remove the installed binary.</td></tr>
        </tbody></DocTable>,
      },
      {
        id: "examples",
        title: "Examples",
        body: <>
          <CopyField value="rc shell Mac"/>
          <CopyField value="rc run Mac -- uname -a"/>
          <CopyField value="rc action run deploy --device Mac --confirm"/>
        </>,
      },
      {
        id: "api-key",
        title: "Use an API key",
        body: <>
          <CopyField value="RC_API_TOKEN='rcsk_...' rc devices"/>
          <CopyField value="rc devices --token 'rcsk_...'"/>
          <p>The CLI parses the <code>rcsk_</code> credential and signs API requests locally. It does not send the private signing key as a bearer token.</p>
        </>,
      },
      {
        id: "local-state",
        title: "Local state",
        body: <>
          <p>RC state is stored under <code>~/.config/rc</code> by default. This includes device identity, RC Lock, device pins, CLI session data, configuration, service logs, and the CLI control private key.</p>
          <p>The CLI uses the same X25519/HKDF-SHA256/AES-256-GCM encrypted control protocol as the browser. See <a href="/docs/security#encrypted-control">Browser and CLI encrypted control</a> for the handshake details.</p>
        </>,
      },
    ],
  };
}
