package ohrats:rc-plugin@0.1.0;

world kernel-host {
    include kernel-plugin;
    import ohrats:rc-keys/host-custody@0.1.0;
    import ohrats:rc-process/environment-host@0.3.0;
    import ohrats:rc-process/filesystem-host@0.3.0;
    import ohrats:rc-process/clock-host@0.3.0;
    import ohrats:rc-process/process-host@0.3.0;
}
