package ohrats:rc-plugin@0.1.0;

world webui-shell {
    include plugin;
    import state-store;
    export ohrats:rc-webui/slots@0.1.0;
    export ohrats:rc-webui/shell@0.1.0;
    export ohrats:rc-http/handler@0.1.0;
}

world webui-app {
    include plugin;
    import ohrats:rc-session/lookup@0.1.0;
    import ohrats:rc-webui/shell@0.1.0;
    export ohrats:rc-http/handler@0.1.0;
}
