export const PORT = Number(Bun.env.PORT || 3000);
export const SSH_DAEMON_PORT = Number(Bun.env.RC_SSH_DAEMON_PORT || 2222);
export const SSH_INTERNAL_PORT = Number(Bun.env.RC_SSH_INTERNAL_PORT || 3001);
export const VERSION = "0.11.0";
export const DATA_DIR = Bun.env.DATA_DIR || "./data";
export const STATIC_DIR = Bun.env.STATIC_DIR || `${import.meta.dir}/../static`;
export const PUBLIC_URL = (Bun.env.PUBLIC_URL || `http://localhost:${PORT}`).replace(/\/$/, "");
export const SETUP_TOKEN = String(Bun.env.RC_SETUP_TOKEN || "").trim();
export const PUBLIC_SIGNUP = Bun.env.RC_PUBLIC_SIGNUP === "1";
export const TURNSTILE_SITE_KEY = String(Bun.env.RC_TURNSTILE_SITE_KEY || "").trim();
export const TURNSTILE_SECRET_KEY = String(Bun.env.RC_TURNSTILE_SECRET_KEY || "").trim();
export const CF_TURN_TOKEN_ID = String(Bun.env.RC_CF_TURN_TOKEN_ID || "").trim();
export const CF_TURN_API_TOKEN = String(Bun.env.RC_CF_TURN_API_TOKEN || "").trim();
export const PUBLIC_SIGNUP_CONFIGURED = PUBLIC_SIGNUP && !!TURNSTILE_SITE_KEY && !!TURNSTILE_SECRET_KEY;
export const RP_ID = new URL(PUBLIC_URL).hostname;
export const DB_PATH = `${DATA_DIR.replace(/\/$/, "")}/rc.db`;
const positiveInt = (name: string, fallback: number) => {
  const value = Number(Bun.env[name]);
  return Number.isInteger(value) && value > 0 ? value : fallback;
};
export const MCP_ACCESS_TTL = positiveInt("RC_MCP_ACCESS_TTL_MINUTES", 15) * 60 * 1000;
export const INVITE_TTL = positiveInt("RC_INVITE_TTL_HOURS", 4) * 60 * 60 * 1000;
export const ENROLLMENT_TTL = positiveInt("RC_ENROLLMENT_TTL_MINUTES", 30) * 60 * 1000;
export const SETUP_COOKIE_TTL = 15 * 60;
export const CEREMONY_TTL = 5 * 60 * 1000;
export const AGENT_CHALLENGE_TTL = 30 * 1000;
export const MAX_WORKSPACES_PER_USER = positiveInt("RC_MAX_WORKSPACES_PER_USER", 10);
export const MAX_DEVICES_PER_WORKSPACE = positiveInt("RC_MAX_DEVICES_PER_WORKSPACE", 25);
export const MAX_API_KEYS_PER_USER = positiveInt("RC_MAX_API_KEYS_PER_USER", 10);
export const MAX_SSH_KEYS_PER_USER = positiveInt("RC_MAX_SSH_KEYS_PER_USER", 20);
